// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SETEcho.Models;

public partial class PurchasedPart
{
    public long Id { get; set; }

    public long Qty { get; set; }

    public long UnitsId { get; set; }

    public string ManufacturerPartNo { get; set; }

    public string DrawingNumber { get; set; }

    public long TypeId { get; set; }

    public string ManufacturerDesc { get; set; }

    public long CompanyId { get; set; }

    public string Notes { get; set; }

    public string Notes2 { get; set; }

    public string Notes3 { get; set; }

    public string Notes4 { get; set; }

    public string Notes5 { get; set; }

    public string Notes6 { get; set; }

    public string Notes7 { get; set; }

    public string Notes8 { get; set; }

    public string Notes9 { get; set; }

    public string Notes10 { get; set; }
}