// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SETEcho.Models;

public partial class PurchaseOrderApproval
{
    public long Id { get; set; }

    public long PurchaseOrderId { get; set; }

    public int SequenceNumber { get; set; }

    public long ApproverUserId { get; set; }

    public string Status { get; set; }

    public DateTime? ActionedAt { get; set; }

    public string Comment { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual PurchaseOrder PurchaseOrder { get; set; }
}