// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SETEcho.Models;

#nullable disable

namespace SETEcho.Migrations
{
    [DbContext(typeof(SETEchoContext))]
    [Migration("20251222144157_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SETEcho.Models.PurchaseOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BillToLocationId")
                        .HasColumnType("bigint")
                        .HasColumnName("bill_to_location_id");

                    b.Property<long>("BuyerId")
                        .HasColumnType("bigint")
                        .HasColumnName("buyer_id");

                    b.Property<DateTime?>("CanceledAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("canceled_at");

                    b.Property<long?>("CanceledByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("canceled_by_user_id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("closed_at");

                    b.Property<long?>("ClosedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("closed_by_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_tbl_POs_created_at");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasColumnName("currency_code")
                        .IsFixedLength();

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_tbl_POs_is_deleted");

                    b.Property<string>("LegacyPoIdentifier")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("legacy_po_identifier");

                    b.Property<long?>("MigrationBatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("migration_batch_id");

                    b.Property<DateOnly?>("NeededByDate")
                        .HasColumnType("date")
                        .HasColumnName("needed_by_date");

                    b.Property<DateOnly>("PoDate")
                        .HasColumnType("date")
                        .HasColumnName("po_date");

                    b.Property<string>("PoNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("po_number");

                    b.Property<long>("ShipToLocationId")
                        .HasColumnType("bigint")
                        .HasColumnName("ship_to_location_id");

                    b.Property<string>("SourceFileName")
                        .HasMaxLength(260)
                        .IsUnicode(false)
                        .HasColumnType("varchar(260)")
                        .HasColumnName("source_file_name");

                    b.Property<int?>("SourceRowNumber")
                        .HasColumnType("int")
                        .HasColumnName("source_row_number");

                    b.Property<string>("SourceSheetName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("source_sheet_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.Property<long>("SupplierId")
                        .HasColumnType("bigint")
                        .HasColumnName("supplier_id");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("total_amount")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_tbl_POs_total_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(sysutcdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_tbl_POs_updated_at");

                    b.Property<long>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("PK_tbl_POs");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex(new[] { "MigrationBatchId" }, "IX_PurchaseOrder_migration_batch");

                    b.HasIndex(new[] { "Status" }, "IX_PurchaseOrder_status");

                    b.HasIndex(new[] { "SupplierId", "PoDate" }, "IX_PurchaseOrder_supplier_date")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "PoNumber" }, "UX_PurchaseOrder_po_number")
                        .IsUnique();

                    b.ToTable("PurchaseOrder", (string)null);
                });

            modelBuilder.Entity("SETEcho.Models.PurchaseOrder1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Customer_ID");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DeliveryDate")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Delivery_Date");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Job")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LineTotal")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Line_Total");

                    b.Property<string>("PoNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PO_Number");

                    b.Property<string>("Qty")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ShippingMethod")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Shipping_Method");

                    b.Property<string>("ShippingTerms")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Shipping_Terms");

                    b.Property<string>("Unit")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UnitPrice")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Unit_Price");

                    b.Property<string>("VendorQuote")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Vendor_Quote");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ShippingTerms" }, "PurchaseOrders$CustomerID");

                    b.HasIndex(new[] { "Id" }, "PurchaseOrders$Id");

                    b.HasIndex(new[] { "ShippingMethod" }, "PurchaseOrders$ShipToId");

                    b.HasIndex(new[] { "CustomerId" }, "PurchaseOrders$VendorID");

                    b.HasIndex(new[] { "DeliveryDate" }, "PurchaseOrders$VendorQuoteId");

                    b.ToTable("PurchaseOrders", (string)null);
                });

            modelBuilder.Entity("SETEcho.Models.PurchaseOrderApproval", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ActionedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("actioned_at");

                    b.Property<long>("ApproverUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("approver_user_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_PurchaseOrderApproval_created_at");

                    b.Property<long>("PurchaseOrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("purchase_order_id");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int")
                        .HasColumnName("sequence_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PurchaseOrderId", "SequenceNumber" }, "IX_POApproval_PO_Seq");

                    b.ToTable("PurchaseOrderApproval", (string)null);
                });

            modelBuilder.Entity("SETEcho.Models.PurchaseOrderLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CostCenterId")
                        .HasColumnType("bigint")
                        .HasColumnName("cost_center_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_PurchaseOrderLine_created_at");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<long?>("GlAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("gl_account_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_PurchaseOrderLine_is_deleted");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("item_description");

                    b.Property<long?>("ItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("item_id");

                    b.Property<string>("LegacyLineIdentifier")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("legacy_line_identifier");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int")
                        .HasColumnName("line_number");

                    b.Property<long?>("MigrationBatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("migration_batch_id");

                    b.Property<long?>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<long>("PurchaseOrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("purchase_order_id");

                    b.Property<decimal>("QuantityOrdered")
                        .HasColumnType("decimal(18, 4)")
                        .HasColumnName("quantity_ordered");

                    b.Property<string>("SourceFileName")
                        .HasMaxLength(260)
                        .IsUnicode(false)
                        .HasColumnType("varchar(260)")
                        .HasColumnName("source_file_name");

                    b.Property<int?>("SourceRowNumber")
                        .HasColumnType("int")
                        .HasColumnName("source_row_number");

                    b.Property<string>("SourceSheetName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("source_sheet_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("unit_of_measure");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 4)")
                        .HasColumnName("unit_price");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(sysutcdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_PurchaseOrderLine_updated_at");

                    b.Property<long>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "GlAccountId", "CostCenterId" }, "IX_POLine_GL");

                    b.HasIndex(new[] { "PurchaseOrderId" }, "IX_POLine_PO");

                    b.HasIndex(new[] { "ProjectId" }, "IX_POLine_Project");

                    b.HasIndex(new[] { "PurchaseOrderId", "LineNumber" }, "UQ_POLine_Per_PO")
                        .IsUnique();

                    b.ToTable("PurchaseOrderLine", (string)null);
                });

            modelBuilder.Entity("SETEcho.Models.PurchaseOrderStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("(sysutcdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_PurchaseOrderStatusHistory_changed_at");

                    b.Property<long>("ChangedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("changed_by_user_id");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("new_status");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("old_status");

                    b.Property<long>("PurchaseOrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("purchase_order_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PurchaseOrderId", "ChangedAt" }, "IX_POStatusHistory_PO")
                        .IsDescending(false, true);

                    b.ToTable("PurchaseOrderStatusHistory", (string)null);
                });

            modelBuilder.Entity("SETEcho.Models.Supplier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address_line2");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Supplier_created_at");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DefaultCurrencyCode")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasColumnName("default_currency_code")
                        .IsFixedLength();

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Supplier_is_active");

                    b.Property<long?>("PaymentTermsId")
                        .HasColumnType("bigint")
                        .HasColumnName("payment_terms_id");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("postal_code");

                    b.Property<string>("StateProvince")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("state_province");

                    b.Property<string>("SupplierCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("supplier_code");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("supplier_name");

                    b.Property<string>("TaxLicenseNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tax_license_number");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(sysutcdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Supplier_updated_at");

                    b.Property<long>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_user_id");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("website");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SupplierName" }, "IX_Supplier_Name");

                    b.HasIndex(new[] { "SupplierCode" }, "UX_Supplier_Code")
                        .IsUnique();

                    b.ToTable("Supplier", (string)null);
                });

            modelBuilder.Entity("SETEcho.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("SETEcho.Models.PurchaseOrder", b =>
                {
                    b.HasOne("SETEcho.Models.Supplier", "Supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("SupplierId")
                        .IsRequired()
                        .HasConstraintName("FK_SupplierID_Supplier");

                    b.HasOne("SETEcho.Models.User", "UpdatedByUser")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("UpdatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_PurchaseOrder_UpdatedByUserId");

                    b.Navigation("Supplier");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("SETEcho.Models.PurchaseOrderApproval", b =>
                {
                    b.HasOne("SETEcho.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("PurchaseOrderApprovals")
                        .HasForeignKey("PurchaseOrderId")
                        .IsRequired()
                        .HasConstraintName("FK_PurchaseOrderApproval_PurchaseOrder");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("SETEcho.Models.PurchaseOrderLine", b =>
                {
                    b.HasOne("SETEcho.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("PurchaseOrderLines")
                        .HasForeignKey("PurchaseOrderId")
                        .IsRequired()
                        .HasConstraintName("FK_POLine_PO");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("SETEcho.Models.PurchaseOrderStatusHistory", b =>
                {
                    b.HasOne("SETEcho.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("PurchaseOrderStatusHistories")
                        .HasForeignKey("PurchaseOrderId")
                        .IsRequired()
                        .HasConstraintName("FK_PurchaseOrderStatusHistory_PurchaseOrder");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("SETEcho.Models.PurchaseOrder", b =>
                {
                    b.Navigation("PurchaseOrderApprovals");

                    b.Navigation("PurchaseOrderLines");

                    b.Navigation("PurchaseOrderStatusHistories");
                });

            modelBuilder.Entity("SETEcho.Models.Supplier", b =>
                {
                    b.Navigation("PurchaseOrders");
                });

            modelBuilder.Entity("SETEcho.Models.User", b =>
                {
                    b.Navigation("PurchaseOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
